INSERT INTO anamnese_perguntas (tipo_anamnese, pergunta, tipo_resposta, opcoes_resposta) VALUES
('PADRAO', 'Você tem ou já teve alguma doença crônica?', 'Sim/Não', NULL),
('PADRAO', 'Se sim, qual doença crônica?', 'Texto', NULL),
('PADRAO', 'Possui alguma restrição médica para exercícios?', 'Sim/Não', NULL),
('PADRAO', 'Já passou por alguma cirurgia relevante?', 'Sim/Não', NULL),
('PADRAO', 'Se sim, qual cirurgia e quando ocorreu?', 'Texto', NULL),
('PADRAO', 'Tem alguma lesão ou dor ao se movimentar?', 'Sim/Não', NULL),
('PADRAO', 'Quantas horas por dia você passa sentado?', 'Numérico', NULL),
('PADRAO', 'Como avalia o seu nível de estresse?', 'Múltipla Escolha', 'Baixo, Médio, Alto'),
('PADRAO', 'Como é a sua qualidade de sono?', 'Múltipla Escolha', 'Boa, Regular, Ruim'),
('PADRAO', 'Você já praticou exercícios físicos antes?', 'Sim/Não', NULL),
('PADRAO', 'Qual é o seu principal objetivo ao treinar?', 'Múltipla Escolha', 'Hipertrofia, Emagrecimento, Condicionamento, Reabilitação, Qualidade de Vida'),
('PADRAO', 'Você faz acompanhamento nutricional?', 'Sim/Não', NULL),

('PARQ', 'Algum médico já disse que você tem problema no coração e recomendou que só fizesse atividade física supervisionada?', 'Sim/Não', NULL),
('PARQ', 'Você sente dor no peito ao realizar atividade física?', 'Sim/Não', NULL),
('PARQ', 'Você sentiu dor no peito no último mês, sem realizar esforço?', 'Sim/Não', NULL),
('PARQ', 'Você tem algum problema ósseo ou articular que pode ser agravado com o exercício físico?', 'Sim/Não', NULL),
('PARQ', 'Algum médico já recomendou que você evitasse exercícios físicos por questões de saúde?', 'Sim/Não', NULL),
('PARQ', 'Você sente tontura ou perda de equilíbrio ao praticar exercícios?', 'Sim/Não', NULL),
('PARQ', 'Você toma alguma medicação para pressão arterial ou coração?', 'Sim/Não', NULL),
('PARQ', 'Você tem histórico de doenças cardiovasculares na família?', 'Sim/Não', NULL),
('PARQ', 'Você já desmaiou ao praticar exercícios físicos?', 'Sim/Não', NULL);