INSERT INTO anamnese_perguntas_padrao (pergunta, tipo_resposta, opcoes_resposta) VALUES
('Você tem ou já teve alguma doença crônica?', 'Sim/Não', NULL),
('Se sim, qual doença crônica?', 'Texto', NULL),
('Possui alguma restrição médica para exercícios?', 'Sim/Não', NULL),
('Já passou por alguma cirurgia relevante?', 'Sim/Não', NULL),
('Se sim, qual cirurgia e quando ocorreu?', 'Texto', NULL),
('Tem alguma lesão ou dor ao se movimentar?', 'Sim/Não', NULL),
('Quantas horas por dia você passa sentado?', 'Numérico', NULL),
('Você fuma?', 'Sim/Não', NULL),
('Você consome bebidas alcoólicas?', 'Sim/Não', NULL),
('Como avalia o seu nível de estresse?', 'Múltipla Escolha', 'Baixo, Médio, Alto'),
('Como é a sua qualidade de sono?', 'Múltipla Escolha', 'Boa, Regular, Ruim'),
('Você já praticou exercícios físicos antes?', 'Sim/Não', NULL),
('Qual é a sua experiência com musculação?', 'Múltipla Escolha', 'Nenhuma, 1-2 anos, 3-5 anos, +5 anos'),
('Qual é o seu principal objetivo ao treinar?', 'Múltipla Escolha', 'Hipertrofia, Emagrecimento, Condicionamento, Reabilitação'),
('Você faz acompanhamento nutricional?', 'Sim/Não', NULL),
('Quantas refeições você faz por dia?', 'Numérico', NULL),
('Consome água regularmente?', 'Numérico', NULL),
('Utiliza suplementos alimentares?', 'Sim/Não', NULL);