package br.com.getmypersonal.model;

public enum ObjetivoTreino {
	HIPERTROFIA,
	FORCA_MAXIMA,
	RESISTENCIA,
	POTENCIA,
	VELOCIDADE_E_AGILIDADE,
	COORDENACAO_E_EQUILIBRIO,
	EMAGRECIMENTO_E_QUEIMA_DE_GORDURA,
	CONDICIONAMENTO_CARDIOVASCULAR,
	RECUPERACAO_ATIVA,
	REAILITACAO__DE_LESAO,
	PREVENCAO_DE_LESAO,
	MOBILIDADE_E_FLEXIBILIDADES;
}
